{{- $name := .Values.name -}}
apiVersion: v1
kind: Service
metadata:
  name: k6-{{ $name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "k6.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "k6.selectorLabels" . | nindent 4 }}
