name: Actions

on:
  push:
    branches:
      - k6_test_qa_adapter

jobs:
  run-basic-checks:
    name: Run linters and unit tests
    runs-on: ubuntu-latest
    environment: QA
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.QA_SDLC_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.QA_SDLC_AWS_SECRET_KEY }}
          aws-region: ${{ secrets.QA_SDLC_AWS_REGION }}
          role-to-assume: ${{ secrets.QA_SDLC_AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 3600
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.QA_SDLC_KUBECONFIG }}
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install Yarn and setup project
        run: |
          npm install -g yarn
          yarn install
          yarn setup
      - name: Use GH CLI to get pr info
        id: get-pr-info
        env:
          GITHUB_TOKEN: ${{ secrets.QA_GITHUB_TOKEN }}
        run: |
          set -x
          pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo '::set-output name=PR_NUMBER::1111' # TODO
          echo "pull request number is ${pull_number}"
          # gh pr view ${pull_number} --json files --jq '.files.[].path' # TODO
          echo '::set-output name=ADAPTERS_LIST::coingecko'
      - name: Build and deploy adapters adapter
        env:
          UNIQUE_NAME: ${{ steps.get-pr-info.outputs.PR_NUMBER }}
          ADAPTER_NAME: ${{ steps.get-pr-info.outputs.ADAPTERS_LIST }}
          IMAGE_PREFIX: ${{ secrets.SDLC_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/adapters/
          IMAGE_TAG: qa-${UNIQUE_NAME}
          GITHUB_TOKEN: ${{ secrets.QA_GITHUB_TOKEN }}
        run: |
          # export IMAGE_PREFIX=${{ secrets.SDLC_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/adapters/
          # export IMAGE_TAG=qa-${UNIQUE_NAME}

          IMAGE_TAG=${IMAGE_TAG} IMAGE_PREFIX=${IMAGE_PREFIX} yarn generate:docker-compose
          docker-compose -f docker-compose.generated.yaml build ${ADAPTER_NAME}-adapter
          docker push ${IMAGE_PREFIX}${ADAPTER_NAME}-adapter:${IMAGE_TAG}
          helm repo add chainlink https://raw.githubusercontent.com/smartcontractkit/charts/gh-pages/ --password ${GITHUB_TOKEN} --username dummy
          yarn qa:adapter start ${ADAPTER_NAME} ${UNIQUE_NAME} ${IMAGE_TAG}
      # - name: Build the k6 payload
      #   env:
      #     UNIQUE_NAME: ${{ steps.get-pr-info.outputs.PR_NUMBER }}
      #     # ADAPTER_NAME: ${{ steps.get-pr-info.outputs.ADAPTERS_LIST }}
      #     IMAGE_PREFIX: ${{ secrets.SDLC_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/k6
      #   run: |
      #     export UNIQUE_NAME=unique-name
      #     export ADAPTER_NAME=coingecko
      #     # export IMAGE_PREFIX=${{ secrets.SDLC_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/k6
      #     # create the config
      #     yarn qa:flux:configure k6payload ${ADAPTER_NAME} ${UNIQUE_NAME}
      #     # Move to the k6 package and build/push
      #     cd ./packages/k6
      #     yarn build
      #     docker build -t ${IMAGE_PREFIX}:${UNIQUE_NAME} .
      #     docker push ${IMAGE_PREFIX}:${UNIQUE_NAME}
      # - name: Deploy k6
      #   env: 
      #     UNIQUE_NAME: ${{ steps.get-pr-info.outputs.PR_NUMBER }}
      #   run: |
      #     cd ./packages/k6
      #     export UNIQUE_NAME=unique-name
      #     helm upgrade k6-${UNIQUE_NAME} ./k8s \
      #       --install \
      #       --namespace adapters \
      #       --create-namespace \
      #       -f ./k8s/values.yaml \
      #       --set image.tag=${UNIQUE_NAME} \
      #       --set name=k6-${UNIQUE_NAME} \
      #       --wait

