name: Actions

on:
  push:
    branches:
      - k6_test_qa_adapter

jobs:
  run-basic-checks:
    name: Run linters and unit tests
    # runs-on: [sdlc-ghr-prod]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install Yarn
        run: npm install -g yarn
      - run: yarn install
      - run: yarn setup
      - run: |
          export UNIQUE_NAME=unique-name
          export ADAPTER_NAME=coingecko
          export IMAGE_PREFIX=${{ secrets.SDLC_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/k6
          # create the config
          yarn qa:flux:configure k6payload ${ADAPTER_NAME} ${UNIQUE_NAME}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_QA_ACCESSKEY }}
          aws-secret-access-key: ${{ secrets.AWS_QA_SECRETKEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 3600
      - run: |
          # Move to the k6 package and build/push
          cd ./packages/k6
          yarn build
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${IMAGE_PREFIX}
          docker build -t ${IMAGE_PREFIX}:${UNIQUE_NAME} .
          docker push ${IMAGE_PREFIX}:${UNIQUE_NAME}
      - run: |
          helm upgrade k6-${UNIQUE_NAME} ./k8s \
            --install \
            --namespace k6-soak \
            --create-namespace \
            -f ./k8s/values.yaml \
            --set image.tag=${UNIQUE_NAME} \
            --set name=k6-${UNIQUE_NAME} \
            --wait
