name: Actions

on:
  push:
    branches:
      - k6_test_qa_adapter

jobs:
  run-basic-checks:
    name: Run linters and unit tests
    # runs-on: [sdlc-ghr-prod]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install Yarn
        run: npm install -g yarn
      - run: yarn install
      - run: yarn setup
      - run: |
          export UNIQUE_NAME=unique-name
          export ADAPTER_NAME=coingecko
          export IMAGE_PREFIX=${{ secrets.SDLC_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/k6
          # create the config
          yarn qa:flux:configure k6payload ${ADAPTER_NAME} ${UNIQUE_NAME}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_QA_ACCESSKEY }}
          aws-secret-access-key: ${{ secrets.AWS_QA_SECRETKEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_QA_ROLE_ARN }}
          role-duration-seconds: 3600
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - run: |
          # Move to the k6 package and build/push
          set -x
          cd ./packages/k6
          echo "yarn build"
          yarn build
          export UNIQUE_NAME=unique-name
          echo "docker build"
          docker build -t ${{ secrets.SDLC_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/k6:${UNIQUE_NAME} .
          echo "docker push"
          docker push ${{ secrets.SDLC_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/k6:${UNIQUE_NAME}
      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
      - run: |
          cd ./packages/k6
          export UNIQUE_NAME=unique-name
          helm upgrade k6-${UNIQUE_NAME} ./k8s \
            --install \
            --namespace k6-soak \
            --create-namespace \
            -f ./k8s/values.yaml \
            --set image.tag=${UNIQUE_NAME} \
            --set name=k6-${UNIQUE_NAME} \
            --wait
